name = "TwPrototypes"
uuid = "9ae22f58-2487-4805-bfc5-386577db46c7"
authors = ["Thomas Wutzler <bgctw@arcor.de>"]
version = "0.2.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
InlineStrings = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"

[extensions]
TwPrototypesAoGExt = ["CairoMakie", "AlgebraOfGraphics"]
TwPrototypesCairoMakieExt = "CairoMakie"
TwPrototypesMCMCChainsExt = "MCMCChains"

[compat]
AlgebraOfGraphics = "0.6, 0.7, 0.8, 0.9, 0.10"
CSV = "0.10"
CairoMakie = "0.10, 0.11, 0.12, 0.13"
ComponentArrays = "0.13, 0.14, 0.15"
DataFrames = "1.4"
InlineStrings = "1.4"
KernelDensity = "0.6"
MCMCChains = "6.0"
Parameters = "0.12"
Pkg = "1.6, 1.7, 1.8, 1.9"
Requires = "1.3"
SimpleTraits = "0.9"
StatsBase = "0.34"
julia = "1.6"

[extras]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"

[workspace]
projects = ["test", "docs"]
